package com.wg.dbp.api.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dbp_transaction
 */
public class DbpTransaction implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   交易id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.transaction_id
     *
     * @mbg.generated
     */
    private String transactionId;

    /**
     * Database Column Remarks:
     *   交易对应的appId
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.app_id
     *
     * @mbg.generated
     */
    private String appId;

    /**
     * Database Column Remarks:
     *   创建时间戳，13位数字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.timestamp
     *
     * @mbg.generated
     */
    private Integer timestamp;

    /**
     * Database Column Remarks:
     *   转出手机号区号，默认86
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.from_mobile_area_code
     *
     * @mbg.generated
     */
    private String fromMobileAreaCode;

    /**
     * Database Column Remarks:
     *   转出手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.from_mobile
     *
     * @mbg.generated
     */
    private String fromMobile;

    /**
     * Database Column Remarks:
     *   转出手机号区号，默认86
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.to_mobile_area_code
     *
     * @mbg.generated
     */
    private String toMobileAreaCode;

    /**
     * Database Column Remarks:
     *   转入手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.to_mobile
     *
     * @mbg.generated
     */
    private String toMobile;

    /**
     * Database Column Remarks:
     *   appId对应的系统的订单id，如果直接转账则没有订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   交易备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * Database Column Remarks:
     *   订单状态，0待验证，1交易成功，2交易取消
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * Database Column Remarks:
     *   逻辑删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * Database Column Remarks:
     *   乐观锁字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbp_transaction.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    public DbpTransaction(Long id, String transactionId, String appId, Integer timestamp, String fromMobileAreaCode, String fromMobile, String toMobileAreaCode, String toMobile, String orderId, String memo, Integer status, Date createdAt, Date updatedAt, Boolean deleted, Integer version) {
        this.id = id;
        this.transactionId = transactionId;
        this.appId = appId;
        this.timestamp = timestamp;
        this.fromMobileAreaCode = fromMobileAreaCode;
        this.fromMobile = fromMobile;
        this.toMobileAreaCode = toMobileAreaCode;
        this.toMobile = toMobile;
        this.orderId = orderId;
        this.memo = memo;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deleted = deleted;
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    public DbpTransaction() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.id
     *
     * @return the value of dbp_transaction.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.id
     *
     * @param id the value for dbp_transaction.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.transaction_id
     *
     * @return the value of dbp_transaction.transaction_id
     *
     * @mbg.generated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.transaction_id
     *
     * @param transactionId the value for dbp_transaction.transaction_id
     *
     * @mbg.generated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.app_id
     *
     * @return the value of dbp_transaction.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.app_id
     *
     * @param appId the value for dbp_transaction.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.timestamp
     *
     * @return the value of dbp_transaction.timestamp
     *
     * @mbg.generated
     */
    public Integer getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.timestamp
     *
     * @param timestamp the value for dbp_transaction.timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Integer timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.from_mobile_area_code
     *
     * @return the value of dbp_transaction.from_mobile_area_code
     *
     * @mbg.generated
     */
    public String getFromMobileAreaCode() {
        return fromMobileAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.from_mobile_area_code
     *
     * @param fromMobileAreaCode the value for dbp_transaction.from_mobile_area_code
     *
     * @mbg.generated
     */
    public void setFromMobileAreaCode(String fromMobileAreaCode) {
        this.fromMobileAreaCode = fromMobileAreaCode == null ? null : fromMobileAreaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.from_mobile
     *
     * @return the value of dbp_transaction.from_mobile
     *
     * @mbg.generated
     */
    public String getFromMobile() {
        return fromMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.from_mobile
     *
     * @param fromMobile the value for dbp_transaction.from_mobile
     *
     * @mbg.generated
     */
    public void setFromMobile(String fromMobile) {
        this.fromMobile = fromMobile == null ? null : fromMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.to_mobile_area_code
     *
     * @return the value of dbp_transaction.to_mobile_area_code
     *
     * @mbg.generated
     */
    public String getToMobileAreaCode() {
        return toMobileAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.to_mobile_area_code
     *
     * @param toMobileAreaCode the value for dbp_transaction.to_mobile_area_code
     *
     * @mbg.generated
     */
    public void setToMobileAreaCode(String toMobileAreaCode) {
        this.toMobileAreaCode = toMobileAreaCode == null ? null : toMobileAreaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.to_mobile
     *
     * @return the value of dbp_transaction.to_mobile
     *
     * @mbg.generated
     */
    public String getToMobile() {
        return toMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.to_mobile
     *
     * @param toMobile the value for dbp_transaction.to_mobile
     *
     * @mbg.generated
     */
    public void setToMobile(String toMobile) {
        this.toMobile = toMobile == null ? null : toMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.order_id
     *
     * @return the value of dbp_transaction.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.order_id
     *
     * @param orderId the value for dbp_transaction.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.memo
     *
     * @return the value of dbp_transaction.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.memo
     *
     * @param memo the value for dbp_transaction.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.status
     *
     * @return the value of dbp_transaction.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.status
     *
     * @param status the value for dbp_transaction.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.created_at
     *
     * @return the value of dbp_transaction.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.created_at
     *
     * @param createdAt the value for dbp_transaction.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.updated_at
     *
     * @return the value of dbp_transaction.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.updated_at
     *
     * @param updatedAt the value for dbp_transaction.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.deleted
     *
     * @return the value of dbp_transaction.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.deleted
     *
     * @param deleted the value for dbp_transaction.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbp_transaction.version
     *
     * @return the value of dbp_transaction.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbp_transaction.version
     *
     * @param version the value for dbp_transaction.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DbpTransaction other = (DbpTransaction) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTransactionId() == null ? other.getTransactionId() == null : this.getTransactionId().equals(other.getTransactionId()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getTimestamp() == null ? other.getTimestamp() == null : this.getTimestamp().equals(other.getTimestamp()))
            && (this.getFromMobileAreaCode() == null ? other.getFromMobileAreaCode() == null : this.getFromMobileAreaCode().equals(other.getFromMobileAreaCode()))
            && (this.getFromMobile() == null ? other.getFromMobile() == null : this.getFromMobile().equals(other.getFromMobile()))
            && (this.getToMobileAreaCode() == null ? other.getToMobileAreaCode() == null : this.getToMobileAreaCode().equals(other.getToMobileAreaCode()))
            && (this.getToMobile() == null ? other.getToMobile() == null : this.getToMobile().equals(other.getToMobile()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getUpdatedAt() == null ? other.getUpdatedAt() == null : this.getUpdatedAt().equals(other.getUpdatedAt()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTransactionId() == null) ? 0 : getTransactionId().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getTimestamp() == null) ? 0 : getTimestamp().hashCode());
        result = prime * result + ((getFromMobileAreaCode() == null) ? 0 : getFromMobileAreaCode().hashCode());
        result = prime * result + ((getFromMobile() == null) ? 0 : getFromMobile().hashCode());
        result = prime * result + ((getToMobileAreaCode() == null) ? 0 : getToMobileAreaCode().hashCode());
        result = prime * result + ((getToMobile() == null) ? 0 : getToMobile().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", transactionId=").append(transactionId);
        sb.append(", appId=").append(appId);
        sb.append(", timestamp=").append(timestamp);
        sb.append(", fromMobileAreaCode=").append(fromMobileAreaCode);
        sb.append(", fromMobile=").append(fromMobile);
        sb.append(", toMobileAreaCode=").append(toMobileAreaCode);
        sb.append(", toMobile=").append(toMobile);
        sb.append(", orderId=").append(orderId);
        sb.append(", memo=").append(memo);
        sb.append(", status=").append(status);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", deleted=").append(deleted);
        sb.append(", version=").append(version);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        transactionId("transaction_id", "transactionId", "VARCHAR", false),
        appId("app_id", "appId", "VARCHAR", false),
        timestamp("timestamp", "timestamp", "INTEGER", false),
        fromMobileAreaCode("from_mobile_area_code", "fromMobileAreaCode", "VARCHAR", false),
        fromMobile("from_mobile", "fromMobile", "VARCHAR", false),
        toMobileAreaCode("to_mobile_area_code", "toMobileAreaCode", "VARCHAR", false),
        toMobile("to_mobile", "toMobile", "VARCHAR", false),
        orderId("order_id", "orderId", "VARCHAR", false),
        memo("memo", "memo", "VARCHAR", false),
        status("status", "status", "INTEGER", false),
        createdAt("created_at", "createdAt", "TIMESTAMP", false),
        updatedAt("updated_at", "updatedAt", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        version("version", "version", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table dbp_transaction
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}