package com.wg.dbp.dao;

import com.wg.dbp.api.model.DbpTransaction;
import com.wg.dbp.api.model.example.DbpTransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbpTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    long countByExample(DbpTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int deleteWithVersionByExample(@Param("version") Integer version, @Param("example") DbpTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int deleteByExample(DbpTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int deleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int insert(DbpTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int insertSelective(DbpTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    DbpTransaction selectOneByExample(DbpTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    List<DbpTransaction> selectByExample(DbpTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    DbpTransaction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    DbpTransaction selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int updateWithVersionByExample(@Param("version") Integer version, @Param("record") DbpTransaction record, @Param("example") DbpTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int updateWithVersionByExampleSelective(@Param("version") Integer version, @Param("record") DbpTransaction record, @Param("example") DbpTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DbpTransaction record, @Param("example") DbpTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DbpTransaction record, @Param("example") DbpTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int updateWithVersionByPrimaryKey(@Param("version") Integer version, @Param("record") DbpTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int updateWithVersionByPrimaryKeySelective(@Param("version") Integer version, @Param("record") DbpTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbpTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbpTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") DbpTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int logicalDeleteWithVersionByExample(@Param("version") Integer version, @Param("example") DbpTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbp_transaction
     *
     * @mbg.generated
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Integer version, @Param("key") Long id);
}